### ISSUE TITLE
not showing anything

### ISSUE THREAD

**Issue by Username69992872** [alexandersokol/sd-model-organizer#11]
not showing anything

![firefox_8omQCcTEqA](https://github.com/alexandersokol/sd-model-organizer/assets/96194225/38626668-8411-4d93-baa9-b66c1e03c4b7)

![firefox_JWUbeXa0TW](https://github.com/alexandersokol/sd-model-organizer/assets/96194225/5e681d3d-3904-4238-a8a4-435452b0a113)

**Comment by alexandersokol** [comment]
did you add any records first?

**Comment by iyh** [comment]
Are there sample .json files for demonstration or Creative Common lists?

**Comment by alexandersokol** [comment]
Done. Local files now should be visible on home screen.

PS: there is no sample .json file for demo, you can use import from civitai.com model url to quickly fill your library.
