### ISSUE TITLE
Download URL

### ISSUE THREAD

**Issue by InfinityARS** [alexandersokol/sd-model-organizer#12]
This is very close to what I was looking for but it misses by requiering a download url even if it's not used. I use sd locally and have all the preview pics + models + data saved already.
Would it be possible to make the download url optional and possibly make it so you can use local files for preview png?

**Comment by alexandersokol** [comment]
Hello, lets add this as enhancement, I will try to look what is possible to do here

**Comment by alexandersokol** [comment]
Done. Download URL is now optional field.
