### ISSUE TITLE
Description editor style in dark mode

### ISSUE THREAD

**Issue by harukaxxxx** [alexandersokol/sd-model-organizer#13]
Description editor's menu in dark mode is hard to read.
![image](https://github.com/alexandersokol/sd-model-organizer/assets/5777085/b5db33cf-dfb8-447b-a904-ad4a55a80b7d)

**Comment by alexandersokol** [comment]
Hello.
As for now you have to use `--theme dark` to enable dark theme support.

**Comment by harukaxxxx** [comment]
`--theme dark` can solve this problem.
