### ISSUE TITLE
Unable to see the cards or table

### ISSUE THREAD

**Issue by munkeyflying** [alexandersokol/sd-model-organizer#14]
![image](https://github.com/alexandersokol/sd-model-organizer/assets/130599053/38385390-605f-4fae-b542-af9669b51353)

![image](https://github.com/alexandersokol/sd-model-organizer/assets/130599053/f87e06db-64ff-4817-af2b-70daacd94cab)

**Comment by alexandersokol** [comment]
Hello!
Did you add records first?

**Comment by munkeyflying** [comment]
That's where I'm a bit confused. Do I need to go through and individually add all of my checkpoints, loras, etc? I've got hundreds of those and it would be a bit of a time consuming process to say the least. Thanks for the reply.

**Comment by alexandersokol** [comment]
Yes, currently there is no way to define what models user currently has, find from where it was downloaded and fill the data.

**Comment by munkeyflying** [comment]
So, as I understand it, this will only show new downloads? If that's so then changing it to also show downloaded files would be fantastic. I just need a good way to organize the models I already have because at the moment they're a bit of a mess.

**Comment by ash0080** [comment]
> So, as I understand it, this will only show new downloads? If that's so then changing it to also show already downloaded files would be fantastic. I just need a good way to organize the models I already have because at the moment they're a bit of a mess.

Yes, at the very least, it should support automatic loading Civitai.info. The current setup is too difficult to use, so I'm giving up on it.

**Comment by alexandersokol** [comment]
Done. Local files are visible on home screen, added model prefill from .info file while adding a new record from local model file.
