### ISSUE TITLE
No sufix with custom download file name

### ISSUE THREAD

**Issue by InfinityARS** [alexandersokol/sd-model-organizer#16]
In case you do not explicitly add a sufix in the "download file name" field (ie: .safetensors), it won't be automatically added and when you donwload you will end up with a unusable file. I believe it should use the one from the original file.

Related to this if you enter in the "download file name" something like [Model_v3.2] the last segment after the dot will not be added to the preview image file and so it won't match the model downloaded. For example:

Model_v3.2 (without the file type extension) & Model_v3.png 

So unusable model with unmatching preview image.

**Comment by alexandersokol** [comment]
There is a case when sometimes it isn't possible to get origin filename from the server because it doesn't provide content-disposition header. So, yes, when you are using download file name you have to add file extension too. I will mark it as a bug to add more clear description for this field.
