### ISSUE TITLE
Prompts using "<" or ">" don't display

### ISSUE THREAD

**Issue by Gerkinfeltser** [alexandersokol/sd-model-organizer#18]
As the title states, prompt word/phrases that start with "<" causes all text after it (& the "<") to not show up.
eg: enter "<this-cool-and-useful-prompt>" in the positive prompt field. result: "Positive Prompt" displays nothing when details are displayed

I realize this may just be an encoding issue that can't be fixed but I thought I'd let you know that I was noticing this behavior. Thank you!

**Comment by alexandersokol** [comment]
Done.
