### ISSUE TITLE
Working with existing downloads?

### ISSUE THREAD

**Issue by tensiondriven** [alexandersokol/sd-model-organizer#19]
Hello - Great extension!!

I don't know if my situation is unique; I have downloaded a couple hundred models, in most cases just the .safetensors file, and would like to organize them.  I was hoping Model Organizer could scan my models folder and make some sense of it, but perhaps this is out of scope.

All of the models are on Civitai, meaning the metadata can be obtained from there.  (I realize this isnt the case for all models, but i think it is a fairly common case.)

Short of actually iterating through and parsing my model files, is there a way I can ask Model Organizer to download these models from Civitai, or perhaps I could use the Civitai addon instead, and download /just/ the metadata, so I don't have to pull the many gigabytes of models again?

I guess this is a feature request for something like "Download metadata without model file".

**Comment by alexandersokol** [comment]
Hello!
Yes, it was already a request to deal something with already downloaded files. And you are right this is might be a good feature to fetch Civitai. Let's add it as enhancement.

**Comment by tensiondriven** [comment]
The civitai addon does a great job of parsing local models and download additional info - I think if this addon could parse the files downloaded by civitai, that would be the full package.

**Comment by alexandersokol** [comment]
Done.
