### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by LLKoder** [alexandersokol/sd-model-organizer#20]
I have dark theme and I have issue in details of models info.

 I don't remember how I set dark theme, maybe it is set with the OS.

![2023-05-27_23-10](https://github.com/alexandersokol/sd-model-organizer/assets/50442676/0b778bb2-457f-40e3-b087-e31120e09fe0)

**Comment by alexandersokol** [comment]
Hello, 
currently you have to use `--theme dark` start parameter to make model organizer use dark theme.

**Comment by LLKoder** [comment]
It help me. Thanks a lot.
Look forward to feature of scan existed base.
