### ISSUE TITLE
Scrape Civitai and Populate Fields

### ISSUE THREAD

**Issue by mobedoor** [alexandersokol/sd-model-organizer#25]
Hi. Thank you for the wonderful extension. 
Could you add a feature to input model's civitai url and populate the fields from it automatically? It would speed up adding models extensively.

**Comment by alexandersokol** [comment]
Hello!
It is already in the develop branch, currently polishing some thing before pushing to main branch.
So you can find new `import/export` button on the top and use `Import Civitai Url` for import.
