### ISSUE TITLE
[Bug]: Add model to MO

### ISSUE THREAD

**Issue by LLKoder** [alexandersokol/sd-model-organizer#29]
I want to add my undownloaded models with MO to MO base, but I can't. I click Add and then time not stop:

![2023-06-20_10-38](https://github.com/alexandersokol/sd-model-organizer/assets/50442676/73a3a853-06d6-4896-99ca-005a7febdff0)

![2023-06-20_10-32](https://github.com/alexandersokol/sd-model-organizer/assets/50442676/6d5c9f30-b177-4722-81d6-063a9cd19206)

![2023-06-20_10-34](https://github.com/alexandersokol/sd-model-organizer/assets/50442676/b1c822e1-d76e-4d9f-8346-76ea95cdf188)

**Comment by alexandersokol** [comment]
Hello, It should be fixed now. Please try to update extension.
