### ISSUE TITLE
[Unfinished Feature]: Remove undownloaded models with MO

### ISSUE THREAD

**Issue by LLKoder** [alexandersokol/sd-model-organizer#32]
![2023-06-21_14-04](https://github.com/alexandersokol/sd-model-organizer/assets/50442676/3452891d-d025-45f8-aabf-7d7619770362)

When I click Remove I get:

![2023-06-21_14-05](https://github.com/alexandersokol/sd-model-organizer/assets/50442676/d2c1d16a-9599-489f-8681-1c152cf16bf7)

Yes the model is not in the base, but it has model file, model preview, moder info and many other model files. Why cannot I remove them?

It would be nice if this remove feature is similar to remove models in base, when user can choose what remove: records or files.

**Comment by alexandersokol** [comment]
Fixed.
