### ISSUE TITLE
[Feature Request] Default Director locations, 

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [alexandersokol/sd-model-organizer#39]
Is there a way to set in the setting of the extension the default locations of the different model, lora, embed ect locations so that the respective model will use that location instead of having to manually do so on each added item at a time because that is very tedious and not everyone has their helpers inside of the default Automatic1111 folder structure.

**Comment by alexandersokol** [comment]
The extension uses custom pathes passed to webui start command arguments like `--ckpt-dir, --vae-dir, --lora-dir, --hypernetwork-dir`. Additionally you can add command argument `--mo-show-dir-settings` to make custom directories settings visible in settings tab for Model Organizer, but keep in mind that the extension will use dirs from settings till you leave these fields empty.
