### ISSUE TITLE
Importing locally stored models

### ISSUE THREAD

**Issue by LoveNug** [alexandersokol/sd-model-organizer#4]
Maybe this is a stupid question, or maybe I'm totally missing the answer in the documentation, but is there a way to import my existing local models into the model organizer interface/database? I only see adding models from download links but not existing local directories.

**Comment by alexandersokol** [comment]
Hello!
Yes, it is possible. When you creating or editing a record that isn't related to any file locally, you have to choose a model type from dropdown, and in case you have any file that isn't related to any other records you should see 'Bind with existing' text box. Please keep in mind it will search files that are related to the models dir type.

Like this one for Lora:
<img width="1550" alt="image" src="https://github.com/alexandersokol/sd-model-organizer/assets/1095159/552cd12a-4587-4239-a506-965732eb821c">
I'm just mentioned it in readme, but seems I need to put proper screenshot too

**Comment by LoveNug** [comment]
Excellent! Thank you for your help. This is a great extension for the WebUI. Thank you for your contribution!
