### ISSUE TITLE
Import JSON not working?

### ISSUE THREAD

**Issue by arcanescroll** [alexandersokol/sd-model-organizer#46]
Hi, any time I try to import a JSON file, it just shows the filename and has a download link at the far right of the page.
![fggdgdgdfd](https://github.com/alexandersokol/sd-model-organizer/assets/111160566/76d82aae-ea67-4143-aaa6-b8d859681647)

**Comment by arcanescroll** [comment]
I don't have the JSON anymore, but I guess it could have been a corrupted file.

**Comment by alexandersokol** [comment]
Ok, lets close it for now. If you face it again please create a new issue.
