### ISSUE TITLE
Compatability with CivitAI Helper .info files 

### ISSUE THREAD

**Issue by ResleyZ** [alexandersokol/sd-model-organizer#8]
Hello, 

Absolutely great idea for an extension! Makes sorting and grouping different models a breeze.

I have one request, I (and I presume many other people as well) have been using [CivitAI Helper](https://civitai.com/models/16768/civitai-helper-sd-webui-civitai-extension) to retrieve and store model information from new and current downloaded models.

Is there a possibility to read or import the .info files and preview images of these models as well, so we can easily access and use the stored information within these files in the model organizer?

This would make it easy to download new models using CivitAI Helper, and keep a better track of the different files using this extension.

**Comment by alexandersokol** [comment]
Hello,
Sound like a good idea, lets mark it as feature request as for now.
I will try to look what I can do.

**Comment by ResleyZ** [comment]
Great to hear, thanks! Hopefully I'll _finally (totally for real)_ will start to completely sort my models into categories and tags 😛

**Comment by navimixu** [comment]
That would be a peak feature to have when it come to auto model organization

**Comment by alexandersokol** [comment]
Done. Now local files are displaying on home screen and while adding a new record info will be prefilled from .info file if it exists.
