### ISSUE TITLE
Civitai filenames sometimes not working 

### ISSUE THREAD

**Issue by joelyoder** [alexandersokol/sd-model-organizer#81]
With the addition of the Civitai API key, the plugin now always downloads a full-size model file, but sometimes it still fails to grab the filename and extension.

For example, I was able to replicate this with the following model: https://civitai.com/models/282765

![Screenshot_20240129-223920.png](https://github.com/alexandersokol/sd-model-organizer/assets/6054295/6eb12fc4-effd-424a-8079-04a25101698e)

From the testing I've done so far, renaming the files works, but there's no upside to using the downloader at that point.

**Comment by joelyoder** [comment]
For posterity, this is a continuation of the comments in #77

**Comment by Learwin** [comment]
With the limited testing I have done it appears to work although preview image download seems to be broken.

**Comment by joelyoder** [comment]
I've not been able to replicate this issue after the latest merge. Thanks for the quick fix!
