### ISSUE TITLE
Preview Image download broken

### ISSUE THREAD

**Issue by Learwin** [alexandersokol/sd-model-organizer#84]
It appears that the image preview download is broken. The file seems to get downloaded but afterwards an exception discards the downloaded file.

Steps to reproduce:
1. Add new record
2. Give preview image link
3. Start download
4. See Error in console

```
[ERROR] cannot identify image file 'F:\\Programme\\Stable Diffusion\\models\\Lora\\tmpddose2g7'
Traceback (most recent call last):
  File "F:\Programme\Stable Diffusion\extensions\sd-model-organizer\scripts\mo\dl\download_manager.py", line 293, in _download_record
    resize_preview_image(temp.name, preview_destination_file_path)
  File "F:\Programme\Stable Diffusion\extensions\sd-model-organizer\scripts\mo\utils.py", line 144, in resize_preview_image
    image = Image.open(input_file)
  File "F:\Programme\Stable Diffusion\venv\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'F:\\Programme\\Stable Diffusion\\models\\Lora\\tmpddose2g7'
ERROR:scripts.mo.environment:cannot identify image file 'F:\\Programme\\Stable Diffusion\\models\\Lora\\tmpddose2g7'
Traceback (most recent call last):
  File "F:\Programme\Stable Diffusion\extensions\sd-model-organizer\scripts\mo\dl\download_manager.py", line 293, in _download_record
    resize_preview_image(temp.name, preview_destination_file_path)
  File "F:\Programme\Stable Diffusion\extensions\sd-model-organizer\scripts\mo\utils.py", line 144, in resize_preview_image
    image = Image.open(input_file)
  File "F:\Programme\Stable Diffusion\venv\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'F:\\Programme\\Stable Diffusion\\models\\Lora\\tmpddose2g7'
```
Image used for preview
https://civitai.com/images/6049419
Model used 
https://civitai.com/models/280194/dragon-eye-fireflies-style-lora?modelVersionId=315548

**Comment by alexandersokol** [comment]
Could you share a link to the image?

**Comment by Learwin** [comment]
Sry github does not let me comment again without closing the issue as resolved and reopening. Idk why it does that
Image used for preview
https://civitai.com/images/6049419
Model used
https://civitai.com/models/280194/dragon-eye-fireflies-style-lora?modelVersionId=315548

**Comment by alexandersokol** [comment]
No worries :)
Are you using exactly this link in the record field for preview?
https://civitai.com/images/6049419

<img width="287" alt="image" src="https://github.com/alexandersokol/sd-model-organizer/assets/1095159/d538ba32-1cbb-482e-b5f3-be405b663d4a">

**Comment by Learwin** [comment]
I also noticed that if you specify a preview url and a model download link that you can only download the preview if the model gets downloaded as well. In my test environment I have to delete the model to be able to try to download the preview image again

![grafik](https://github.com/alexandersokol/sd-model-organizer/assets/6223515/d9b0a665-8b2f-4c8e-ac6e-b25afe4e72e2)

**Comment by alexandersokol** [comment]
I see the problem. You simply need to put a direct link to the image that ends with .jpg or .png. 
Try to make a right mouse click on image, select "Copy image address" and paste into this field.

You should get something like this:
`https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/a458a229-41ad-4042-8e6d-e6f84ac3356b/original=true/ComfyUI_1339.jpeg`

**Comment by alexandersokol** [comment]
Probably the best way to add model from civitAI is to use "Import/Export" -> "Import Civitai URL". There you can select model/version/image to import to a new record.

Pay attention that "video" also displaying in the preview selection, but they aren't correctly visible

**Comment by Learwin** [comment]
> Probably the best way to add model from civitAI is to use "Import/Export" -> "Import Civitai URL". There you can select model/version/image to import to a new record.
> 
> Pay attention that "video" also displaying in the preview selection, but they aren't correctly visible

I'm learning something new everyday. I never noticed the "Import Civitai URL". Cheers.
