### ISSUE TITLE
Civitai Model REST API changes

### ISSUE THREAD

**Issue by Learwin** [alexandersokol/sd-model-organizer#91]
Seems like Civitai's REST API updated recently and they removed at least the field `updated_at` when getting a model.

Error occurs here causing the method call to interupt and not finish:
https://github.com/alexandersokol/sd-model-organizer/blob/main/scripts/mo/data/mapping_utils.py#L8

Seems like this field isn't used anywhere so it can just be commented out.

I haven't used my local Stable Diffusion installation this week as Civitai had major outtages. If I find more broken REST requests I'll add additional comments to this issue.

**Comment by alexandersokol** [comment]
Thank you for the report!
Should be fixed now:
https://github.com/alexandersokol/sd-model-organizer/pull/92
