### ISSUE TITLE
model: "xyz.safetensors" not found on CivitaAI servers

### ISSUE THREAD

**Issue by hobojoker** [alexandersokol/sd-model-organizer#93]
When trying to update model info and tags, I keep seeing this response in the console for a lot of models:

"model: "foo.safetensors" not found on CivitaAI servers"

I have an active API and it's registered in the settings for stable diffusion. The models it's not finding are available on civitai - I'm not sure what is preventing the extension from finding the models or how to address this

**Comment by harukaxxxx** [comment]
Can you let me know how you reproduced this issue? Did you import the record through "Import Civitai URL"? Can you provide the Civitai URL that's causing the issue?

**Comment by hobojoker** [comment]
I think this might have been an issue due to the transitioning/implementation of the new filtering on civitai, but I have switched completely to comfyui now so I can't really do much to support this issue, if it's still an issue.
